(function(global){
  "use strict";
  /* Quest4Bugs 読み仮名データ（フレーズ -> ルビHTML）。shared/furigana.js が使う。
     正確さ最優先で人手検証済みの注釈を登録する。順次拡張。
     カバー範囲: えいたんご BASIC/FIELD2 の和訳（漢字を含む語） */
  if(!global.Furi){ global.__Q4B_YOMI=global.__Q4B_YOMI||{}; }
  var DATA={"水":"<ruby>水<rt>みず</rt></ruby>","川":"<ruby>川<rt>かわ</rt></ruby>","湖":"<ruby>湖<rt>みずうみ</rt></ruby>","池":"<ruby>池<rt>いけ</rt></ruby>","魚":"<ruby>魚<rt>さかな</rt></ruby>","鳥":"<ruby>鳥<rt>とり</rt></ruby>","木":"<ruby>木<rt>き</rt></ruby>","花":"<ruby>花<rt>はな</rt></ruby>","草":"<ruby>草<rt>くさ</rt></ruby>","葉":"<ruby>葉<rt>は</rt></ruby>","石":"<ruby>石<rt>いし</rt></ruby>","砂":"<ruby>砂<rt>すな</rt></ruby>","泥":"<ruby>泥<rt>どろ</rt></ruby>","橋":"<ruby>橋<rt>はし</rt></ruby>","雨":"<ruby>雨<rt>あめ</rt></ruby>","雲":"<ruby>雲<rt>くも</rt></ruby>","空":"<ruby>空<rt>そら</rt></ruby>","太陽":"<ruby>太陽<rt>たいよう</rt></ruby>","風":"<ruby>風<rt>かぜ</rt></ruby>","音":"<ruby>音<rt>おと</rt></ruby>","昆虫":"<ruby>昆虫<rt>こんちゅう</rt></ruby>","虫":"<ruby>虫<rt>むし</rt></ruby>","翼":"<ruby>翼<rt>つばさ</rt></ruby>","巣":"<ruby>巣<rt>す</rt></ruby>","卵":"<ruby>卵<rt>たまご</rt></ruby>","森":"<ruby>森<rt>もり</rt></ruby>","山":"<ruby>山<rt>やま</rt></ruby>","野原":"<ruby>野原<rt>のはら</rt></ruby>","道路":"<ruby>道路<rt>どうろ</rt></ruby>","小道":"<ruby>小道<rt>こみち</rt></ruby>","木材":"<ruby>木材<rt>もくざい</rt></ruby>","火":"<ruby>火<rt>ひ</rt></ruby>","光":"<ruby>光<rt>ひかり</rt></ruby>","色":"<ruby>色<rt>いろ</rt></ruby>","形":"<ruby>形<rt>かたち</rt></ruby>","大きさ":"<ruby>大<rt>おお</rt></ruby>きさ","動物":"<ruby>動物<rt>どうぶつ</rt></ruby>","植物":"<ruby>植物<rt>しょくぶつ</rt></ruby>","種":"<ruby>種<rt>たね</rt></ruby>","根":"<ruby>根<rt>ね</rt></ruby>","地面":"<ruby>地面<rt>じめん</rt></ruby>","穴":"<ruby>穴<rt>あな</rt></ruby>","泳ぐ":"<ruby>泳<rt>およ</rt></ruby>ぐ","跳ぶ":"<ruby>跳<rt>と</rt></ruby>ぶ","飛ぶ":"<ruby>飛<rt>と</rt></ruby>ぶ","捕まえる":"<ruby>捕<rt>つか</rt></ruby>まえる","落ちる":"<ruby>落<rt>お</rt></ruby>ちる","育つ":"<ruby>育<rt>そだ</rt></ruby>つ","浮かぶ":"<ruby>浮<rt>う</rt></ruby>かぶ","沈む":"<ruby>沈<rt>しず</rt></ruby>む","登る":"<ruby>登<rt>のぼ</rt></ruby>る","歩く":"<ruby>歩<rt>ある</rt></ruby>く","走る":"<ruby>走<rt>はし</rt></ruby>る","見る":"<ruby>見<rt>み</rt></ruby>る","じっと見る":"じっと<ruby>見<rt>み</rt></ruby>る","聞こえる":"<ruby>聞<rt>き</rt></ruby>こえる","見つける":"<ruby>見<rt>み</rt></ruby>つける","隠れる":"<ruby>隠<rt>かく</rt></ruby>れる","動く":"<ruby>動<rt>うご</rt></ruby>く","押す":"<ruby>押<rt>お</rt></ruby>す","引く":"<ruby>引<rt>ひ</rt></ruby>く","投げる":"<ruby>投<rt>な</rt></ruby>げる","触る":"<ruby>触<rt>さわ</rt></ruby>る","待つ":"<ruby>待<rt>ま</rt></ruby>つ","始める":"<ruby>始<rt>はじ</rt></ruby>める","止まる":"<ruby>止<rt>と</rt></ruby>まる","数える":"<ruby>数<rt>かぞ</rt></ruby>える","小さい":"<ruby>小<rt>ちい</rt></ruby>さい","大きい":"<ruby>大<rt>おお</rt></ruby>きい","長い":"<ruby>長<rt>なが</rt></ruby>い","短い":"<ruby>短<rt>みじか</rt></ruby>い","深い":"<ruby>深<rt>ふか</rt></ruby>い","濡れた":"<ruby>濡<rt>ぬ</rt></ruby>れた","乾いた":"<ruby>乾<rt>かわ</rt></ruby>いた","汚い":"<ruby>汚<rt>きたな</rt></ruby>い","静かな":"<ruby>静<rt>しず</rt></ruby>かな","野生の":"<ruby>野生<rt>やせい</rt></ruby>の","速い":"<ruby>速<rt>はや</rt></ruby>い","遅い":"<ruby>遅<rt>おそ</rt></ruby>い","緑の":"<ruby>緑<rt>みどり</rt></ruby>の","明るい":"<ruby>明<rt>あか</rt></ruby>るい","暗い":"<ruby>暗<rt>くら</rt></ruby>い","冷たい":"<ruby>冷<rt>つめ</rt></ruby>たい","暖かい":"<ruby>暖<rt>あたた</rt></ruby>かい","近くに":"<ruby>近<rt>ちか</rt></ruby>くに","下に":"<ruby>下<rt>した</rt></ruby>に","上に":"<ruby>上<rt>うえ</rt></ruby>に"};
  if(global.Furi&&global.Furi.add){ global.Furi.add(DATA); }
  else { global.__Q4B_YOMI=global.__Q4B_YOMI||{}; for(var k in DATA){ global.__Q4B_YOMI[k]=DATA[k]; } }
})(window);
